//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int id { get; set; }
        public string path { get; set; }
        public string name { get; set; }
        public string mime { get; set; }
        public Nullable<decimal> size { get; set; }
        public Nullable<int> fk_order { get; set; }
        public Nullable<int> fk_contract { get; set; }
    
        public virtual contract contract { get; set; }
        public virtual generic_order generic_order { get; set; }
    }
}
