//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class generic_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public generic_order()
        {
            this.delivery_method = new HashSet<delivery_method>();
            this.files = new HashSet<file>();
            this.order_resource = new HashSet<order_resource>();
            this.payments = new HashSet<payment>();
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<float> payed_amount { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public Nullable<sbyte> direction { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> init_date { get; set; }
        public string dest_addr { get; set; }
        public string dest_zipcode { get; set; }
        public Nullable<int> fk_status { get; set; }
        public Nullable<int> fk_profile { get; set; }
        public Nullable<int> fk_distributor { get; set; }
        public Nullable<int> fk_supplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_method> delivery_method { get; set; }
        public virtual distributor distributor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual order_status order_status { get; set; }
        public virtual profile profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_resource> order_resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment> payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
    }
}
