//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furniture.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class furnitureEntities : DbContext
    {
        public furnitureEntities()
            : base("name=furnitureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contract> contracts { get; set; }
        public virtual DbSet<contract_type> contract_type { get; set; }
        public virtual DbSet<delivery_method> delivery_method { get; set; }
        public virtual DbSet<distributor> distributors { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<generic_order> generic_order { get; set; }
        public virtual DbSet<m_unit> m_unit { get; set; }
        public virtual DbSet<order_resource> order_resource { get; set; }
        public virtual DbSet<order_status> order_status { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<payment_type> payment_type { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_resource> product_resource { get; set; }
        public virtual DbSet<product_resource_transaction> product_resource_transaction { get; set; }
        public virtual DbSet<product_transaction> product_transaction { get; set; }
        public virtual DbSet<product_type> product_type { get; set; }
        public virtual DbSet<profile> profiles { get; set; }
        public virtual DbSet<resource> resources { get; set; }
        public virtual DbSet<resource_transaction> resource_transaction { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
    }
}
