//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_resource
    {
        public int id { get; set; }
        public Nullable<float> amount { get; set; }
        public Nullable<int> fk_resource { get; set; }
        public Nullable<int> fk_order { get; set; }
    
        public virtual generic_order generic_order { get; set; }
        public virtual resource resource { get; set; }
    }
}
