//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_resource()
        {
            this.product_resource_transaction = new HashSet<product_resource_transaction>();
        }
    
        public int id { get; set; }
        public Nullable<float> amount { get; set; }
        public Nullable<int> fk_product { get; set; }
        public Nullable<int> fk_resource { get; set; }
    
        public virtual product product { get; set; }
        public virtual resource resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_resource_transaction> product_resource_transaction { get; set; }
    }
}
