//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.product_resource = new HashSet<product_resource>();
            this.product_resource_transaction = new HashSet<product_resource_transaction>();
            this.product_transaction = new HashSet<product_transaction>();
        }
    
        public int id { get; set; }
        public Nullable<float> single_price { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> part_count { get; set; }
        public Nullable<float> est_single_cost { get; set; }
        public Nullable<int> fk_order { get; set; }
        public Nullable<int> fk_product_type { get; set; }
    
        public virtual generic_order generic_order { get; set; }
        public virtual product_type product_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_resource> product_resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_resource_transaction> product_resource_transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_transaction> product_transaction { get; set; }
    }
}
