//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int id { get; set; }
        public Nullable<float> amount { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<sbyte> direction { get; set; }
        public Nullable<int> fk_type { get; set; }
        public Nullable<int> fk_order { get; set; }
    
        public virtual generic_order generic_order { get; set; }
        public virtual payment_type payment_type { get; set; }
    }
}
