//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public resource()
        {
            this.order_resource = new HashSet<order_resource>();
            this.product_resource = new HashSet<product_resource>();
            this.product_transaction = new HashSet<product_transaction>();
        }
    
        public int id { get; set; }
        public Nullable<float> left_amount { get; set; }
        public Nullable<float> unit_price { get; set; }
        public Nullable<int> fk_res_trans { get; set; }
        public Nullable<int> fk_m_unit { get; set; }
    
        public virtual m_unit m_unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_resource> order_resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_resource> product_resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_transaction> product_transaction { get; set; }
        public virtual resource_transaction resource_transaction { get; set; }
    }
}
